"""add transaction payment fields

Revision ID: 0c1a6734adee
Revises: 8cd7e0b04572
Create Date: 2026-09-04 01:24:48.677557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a6734adee'
down_revision: Union[str, None] = '8cd7e0b04572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('gateway', sa.String(length=128), nullable=True))
    op.add_column('transactions', sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_index(op.f('ix_transactions_gateway'), 'transactions', ['gateway'], unique=False)
    op.create_index(op.f('ix_transactions_payment_method'), 'transactions', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_payment_method'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway'), table_name='transactions')
    op.drop_column('transactions', 'attempt_number')
    op.drop_column('transactions', 'gateway')
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
